basePath: /api/
definitions:
  handlers.QueryRequest:
    properties:
      query:
        type: string
    type: object
  utils.ErrorResponse:
    properties:
      code:
        type: integer
      data:
        additionalProperties: true
        type: object
      message:
        type: string
    type: object
  utils.SuccessResponse:
    properties:
      data: {}
      message:
        type: string
      success:
        type: boolean
    type: object
host: localhost:8090
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server for a reminder application.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: RemiAq API
  version: "1.0"
paths:
  /rdelete:
    delete:
      consumes:
      - application/json
      description: Executes a raw DELETE SQL query against the database.
      parameters:
      - description: Query object
        in: body
        name: query
        required: true
        schema:
          $ref: '#/definitions/handlers.QueryRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Successfully executed query
          schema:
            $ref: '#/definitions/utils.SuccessResponse'
        "400":
          description: Invalid request payload
          schema:
            $ref: '#/definitions/utils.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/utils.ErrorResponse'
      summary: Execute a DELETE query
      tags:
      - Raw Query
  /rinsert:
    post:
      consumes:
      - application/json
      description: Executes a raw INSERT SQL query against the database.
      parameters:
      - description: Query object
        in: body
        name: query
        required: true
        schema:
          $ref: '#/definitions/handlers.QueryRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Successfully executed query
          schema:
            $ref: '#/definitions/utils.SuccessResponse'
        "400":
          description: Invalid request payload
          schema:
            $ref: '#/definitions/utils.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/utils.ErrorResponse'
      summary: Execute an INSERT query
      tags:
      - Raw Query
  /rquery:
    post:
      consumes:
      - application/json
      description: Executes a raw SELECT SQL query against the database.
      parameters:
      - description: Query object
        in: body
        name: query
        required: true
        schema:
          $ref: '#/definitions/handlers.QueryRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Successfully executed query
          schema: {}
        "400":
          description: Invalid request payload
          schema:
            $ref: '#/definitions/utils.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/utils.ErrorResponse'
      summary: Execute a SELECT query
      tags:
      - Raw Query
  /rupdate:
    put:
      consumes:
      - application/json
      description: Executes a raw UPDATE SQL query against the database.
      parameters:
      - description: Query object
        in: body
        name: query
        required: true
        schema:
          $ref: '#/definitions/handlers.QueryRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Successfully executed query
          schema:
            $ref: '#/definitions/utils.SuccessResponse'
        "400":
          description: Invalid request payload
          schema:
            $ref: '#/definitions/utils.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/utils.ErrorResponse'
      summary: Execute an UPDATE query
      tags:
      - Raw Query
swagger: "2.0"
